### ISSUE TITLE
windows exe - 谢谢大佬的肩膀！

### ISSUE THREAD

**Issue by chenyingchun0312** [vankubo/uvConvertor#1]
谢谢大佬的肩膀！我试了一下，很有用...

附件是我编译的windows平台的exe
[uvConvertor-CLI.zip](https://github.com/vankubo/uvConvertor/files/11740566/uvConvertor-CLI.zip)

**Comment by themql** [comment]
> 谢谢大佬的肩膀！我试了一下，很有用...
> 
> 附件是我编译的windows平台的exe [uvConvertor-CLI.zip](https://github.com/vankubo/uvConvertor/files/11740566/uvConvertor-CLI.zip)

您好，

我下载了您提供的二进制文件，但当运行它时，我碰到了一点麻烦：

当我直接运行它时，并没有理想的配置文件输出，而是返回了错误码-1073741819；当我试着以管理员权限运行它时，没有错误码但依旧没有输出。

请问您有碰到过这个问题吗？

**Comment by chenyingchun0312** [comment]
> > 谢谢大佬的肩膀！我试了一下，很有用...
> > 附件是我编译的windows平台的exe [uvConvertor-CLI.zip](https://github.com/vankubo/uvConvertor/files/11740566/uvConvertor-CLI.zip)
> 
> 您好，
> 
> 我下载了您提供的二进制文件，但当运行它时，我碰到了一点麻烦：
> 
> 当我直接运行它时，并没有理想的配置文件输出，而是返回了错误码-1073741819；当我试着以管理员权限运行它时，没有错误码但依旧没有输出。
> 
> 请问您有碰到过这个问题吗？
没有遇到过这个问题呢，要不你直接clang++自己编译试试
