### ISSUE TITLE
感谢分享！

### ISSUE THREAD

**Issue by hclcq** [vankubo/uvConvertor#6]
最近正好换了clangd插件来做stm32工程的编辑，有很大帮助。但我自己使用时有些问题，clangd插件好像不能识别"arguments"标签下的第一个inclunde路径，导致有些头文件找不到。

**Comment by chenyingchun0312** [comment]
我看新版本已经解决了这个问题, 优化了compile_command.json文件, 这个PR: https://github.com/vankubo/uvConvertor/pull/4
